Add MatchGroup helper methods
relex/aini pull request #6
Opened 2021-07-08 14:04 UTC by bemyak

Add a few helper methods to assist in looking for groups in different lists.

2021-07-08 14:25 UTC, jiping-s requested changes

2021-07-08 14:25 UTC, jiping-s commented on aini.go
>  // Match looks for a hosts that match the pattern
`a hosts`

and several `a groups` below

2021-07-08 14:25 UTC, jiping-s commented on aini.go
> +		if m, err := path.Match(pattern, host.Name); err == nil && m {
Should `err` be returned here, since it indicates `pattern` is invalid? (or log or panic...?)

2021-07-09 11:10 UTC, jiping-s approved these changes

2021-07-09 11:54 UTC, bemyak commented
@jiping-s , thanks for the review. 

The errors are originated from copy-pasted code :) I came up with a better approach and deprecated the old method, should be good to go now.

2021-07-09 12:08 UTC, merged